package com.tint.wotn.input;

public enum Inputs {
	BATTLE_SCREEN,
	BATTLE_SCREEN_UI,
	GESTURE,
	MAIN_MENU_SCREEN_UI,
	MULTIPLAYER_SCREEN,
	MULTIPLAYER_SCREEN_UI,
	CAMPAIGN_SCREEN,
	CAMPAIGN_SCREEN_UI,
	END_SCREEN_UI;
}
